In [1]:
import json

from ray.rllib.env.tcp_client_inference_env_runner import torch
from sqlalchemy import create_engine, text
import pandas as pd

# 数据库配置
import pickle
with open('./datasets/sql_token.pkl', 'rb') as f:
    DB_URI = pickle.load(f)

engine = create_engine(DB_URI)
DATA_JSON_PATH = './datasets/data.json'

# 加载分类数据
with open(DATA_JSON_PATH) as f:
    group_map = json.load(f)


In [5]:
for group_idx, (group_name, group_list) in enumerate(group_map.items()):
    for group_data in group_list:
        if group_name == 'stock1' and group_data['industry_code'] in ['270000', '480000']:
            print(group_name, group_data, )
        # break
    # break

stock1 {'tu_type': 'stock', 'year': 1, 'industry_code': '270000', 'code_list': ['560100', '015593', '012320', '012319', '013339', '013340', '014418', '014419', '016052', '014193', '014194', '013869', '013870', '014587', '014588', '015773', '013242', '014854', '014855', '013465', '013466', '013005', '013004', '015075', '013622', '014299', '014300', '015199', '015198', '014377', '014376', '012496', '012497', '012696', '012697']}
stock1 {'tu_type': 'stock', 'year': 1, 'industry_code': '480000', 'code_list': ['013233', '013234', '013355', '014198', '501219', '011225', '011224', '014187', '014188', '012912', '012911', '013490', '013491']}


In [8]:
for i in range(len(group_map['stock1'])):
    if group_map['stock1'][i]['industry_code'] == '270000':
        print(group_map['stock1'][i])

for i in range(len(group_map['stock1'])):
    if group_map['stock1'][i]['industry_code'] == '480000':
        print(group_map['stock1'][i])

{'tu_type': 'stock', 'year': 1, 'industry_code': '270000', 'code_list': ['560100', '015593', '012320', '012319', '013339', '013340', '014418', '014419', '016052', '014193', '014194', '013869', '013870', '014587', '014588', '015773', '013242', '014854', '014855', '013465', '013466', '013005', '013004', '015075', '013622', '014299', '014300', '015199', '015198', '014377', '014376', '012496', '012497', '012696', '012697']}
{'tu_type': 'stock', 'year': 1, 'industry_code': '480000', 'code_list': ['013233', '013234', '013355', '014198', '501219', '011225', '011224', '014187', '014188', '012912', '012911', '013490', '013491']}


In [18]:
pred_value = 'accnav'
sql = text(f"SELECT fund_code, date, nav, accnav, adj_nav FROM b_fund_nav_details_new WHERE fund_code IN :codes AND date BETWEEN :start AND :end ORDER BY date")
df = pd.read_sql_query(
    sql.bindparams(codes=tuple(['013152']), start='2020-07-13', end='2025-03-8'),
    engine
)
df

fund_code        date     nav  accnav  adj_nav
0      013152  2021-08-12  1.9100  1.9100   1.9100
1      013152  2021-08-13  1.9016  1.9016   1.9016
2      013152  2021-08-16  1.9089  1.9089   1.9089
3      013152  2021-08-17  1.8223  1.8223   1.8223
4      013152  2021-08-18  1.8289  1.8289   1.8289
..        ...         ...     ...     ...      ...
874    013152  2025-03-03  1.0584  1.0584   1.0584
875    013152  2025-03-04  1.0469  1.0469   1.0469
876    013152  2025-03-05  1.0460  1.0460   1.0460
877    013152  2025-03-06  1.0603  1.0603   1.0603
878    013152  2025-03-07  1.0735  1.0735   1.0735

[879 rows x 5 columns]

In [26]:
df_stamp = pd.to_datetime(df['date'])
df_stamp[1].year, df_stamp[1].month, df_stamp[1].day, df_stamp[1].weekday()

(2021, 8, 13, 4)

In [3]:
from c_model_center import Model
from a_data_center import DataModule
# Experiment Settings, logger, plotter
from utils.exp_config import get_config
config = get_config()
datamodule = DataModule(config)
model = Model(datamodule, config)
datamodule.test_x[0]

[2020 1 1 2 428.1]
(52696, 5) (52696,)


array([[2.02000000e+03, 1.00000000e+01, 1.80000000e+01, 6.00000000e+00,
        1.96523350e-02],
       [2.02000000e+03, 1.00000000e+01, 1.80000000e+01, 6.00000000e+00,
        2.09545642e-02],
       [2.02000000e+03, 1.00000000e+01, 1.80000000e+01, 6.00000000e+00,
        2.25172546e-02],
       [2.02000000e+03, 1.00000000e+01, 1.80000000e+01, 6.00000000e+00,
        2.30380986e-02],
       [2.02000000e+03, 1.00000000e+01, 1.80000000e+01, 6.00000000e+00,
        2.32985597e-02],
       [2.02000000e+03, 1.00000000e+01, 1.80000000e+01, 6.00000000e+00,
        2.46007890e-02],
       [2.02000000e+03, 1.00000000e+01, 1.80000000e+01, 6.00000000e+00,
        2.40798667e-02],
       [2.02000000e+03, 1.00000000e+01, 1.80000000e+01, 6.00000000e+00,
        2.38194838e-02],
       [2.02000000e+03, 1.00000000e+01, 1.80000000e+01, 6.00000000e+00,
        2.38194838e-02],
       [2.02000000e+03, 1.00000000e+01, 1.80000000e+01, 6.00000000e+00,
        2.59030182e-02],
       [2.02000000e+03, 1.0000

In [4]:
datamodule.valid_x[0]

array([[6.1470e+03, 2.0230e+03, 3.0000e+00, 2.0000e+01, 0.0000e+00,
        1.1335e+00],
       [6.1470e+03, 2.0230e+03, 3.0000e+00, 2.1000e+01, 1.0000e+00,
        1.1530e+00],
       [6.1470e+03, 2.0230e+03, 3.0000e+00, 2.2000e+01, 2.0000e+00,
        1.1603e+00],
       [6.1470e+03, 2.0230e+03, 3.0000e+00, 2.3000e+01, 3.0000e+00,
        1.1633e+00],
       [6.1470e+03, 2.0230e+03, 3.0000e+00, 2.4000e+01, 4.0000e+00,
        1.1566e+00],
       [6.1470e+03, 2.0230e+03, 3.0000e+00, 2.7000e+01, 0.0000e+00,
        1.1563e+00],
       [6.1470e+03, 2.0230e+03, 3.0000e+00, 2.8000e+01, 1.0000e+00,
        1.1477e+00],
       [6.1470e+03, 2.0230e+03, 3.0000e+00, 2.9000e+01, 2.0000e+00,
        1.1516e+00],
       [6.1470e+03, 2.0230e+03, 3.0000e+00, 3.0000e+01, 3.0000e+00,
        1.1543e+00],
       [6.1470e+03, 2.0230e+03, 3.0000e+00, 3.1000e+01, 4.0000e+00,
        1.1748e+00],
       [6.1470e+03, 2.0230e+03, 4.0000e+00, 3.0000e+00, 0.0000e+00,
        1.1734e+00],
       [6.1470e+03, 2

In [2]:
datamodule.train_x[0]

array([[6.1470e+03, 2.0200e+03, 7.0000e+00, 1.3000e+01, 0.0000e+00,
        1.3893e+00],
       [6.1470e+03, 2.0200e+03, 7.0000e+00, 1.4000e+01, 1.0000e+00,
        1.3598e+00],
       [6.1470e+03, 2.0200e+03, 7.0000e+00, 1.5000e+01, 2.0000e+00,
        1.3418e+00],
       [6.1470e+03, 2.0200e+03, 7.0000e+00, 1.6000e+01, 3.0000e+00,
        1.2626e+00],
       [6.1470e+03, 2.0200e+03, 7.0000e+00, 1.7000e+01, 4.0000e+00,
        1.2623e+00],
       [6.1470e+03, 2.0200e+03, 7.0000e+00, 2.0000e+01, 0.0000e+00,
        1.2874e+00],
       [6.1470e+03, 2.0200e+03, 7.0000e+00, 2.1000e+01, 1.0000e+00,
        1.2885e+00],
       [6.1470e+03, 2.0200e+03, 7.0000e+00, 2.2000e+01, 2.0000e+00,
        1.3094e+00],
       [6.1470e+03, 2.0200e+03, 7.0000e+00, 2.3000e+01, 3.0000e+00,
        1.3088e+00],
       [6.1470e+03, 2.0200e+03, 7.0000e+00, 2.4000e+01, 4.0000e+00,
        1.2527e+00],
       [6.1470e+03, 2.0200e+03, 7.0000e+00, 2.7000e+01, 0.0000e+00,
        1.2464e+00],
       [6.1470e+03, 2

In [1]:
9 * 160 + 200 * 7

2840

In [79]:
a = torch.randn(2, 2)

In [80]:
import torch
# a = torch.tensor([1, 1, 12, 9, 8, 2, 11], dtype=torch.float32).unsqueeze(1)  # shape (6, 1)
a /= a.max()
# cls = torch.randn(a.shape[-1]).unsqueeze(-1)
cls = torch.randn(2, 2)
a = torch.cat((cls, a), dim=0)
dk = a.shape[-1]
qk = torch.matmul(a, a.T) / dk  # shape (6, 6)
weight = torch.softmax(qk, dim=-1)
out = torch.matmul(weight, a)
print(a)

tensor([[-0.0626,  0.5855],
        [-0.7740,  0.5836],
        [ 1.0000,  0.2283],
        [-0.5410, -1.4340]])


In [81]:
print(qk)

tensor([[ 0.1734,  0.1951,  0.0355, -0.4029],
        [ 0.1951,  0.4698, -0.3204, -0.2091],
        [ 0.0355, -0.3204,  0.5261, -0.4342],
        [-0.4029, -0.2091, -0.4342,  1.1745]])


In [82]:
print(weight)

tensor([[0.2894, 0.2958, 0.2521, 0.1627],
        [0.2793, 0.3676, 0.1668, 0.1864],
        [0.2526, 0.1769, 0.4125, 0.1579],
        [0.1246, 0.1513, 0.1208, 0.6034]])


In [83]:

print(out)

tensor([[-0.0829,  0.1664],
        [-0.2361,  0.1488],
        [ 0.1743,  0.1189],
        [-0.3305, -0.6764]])


In [17]:
import pandas as pd
import numpy as np
df = pd.read_excel('./datasets/lottery/pl3_desc.xls', header=1)
timestamps = pd.to_datetime(df['开奖日期'])
timestamps = np.array([[ts.year, ts.month, ts.day, ts.weekday()] for ts in timestamps])
x = np.array(df['号']).reshape(-1, 1)
# timestamps
x = np.concatenate((timestamps, x), axis=-1)
df

开奖期号        开奖日期  开  奖  号      投注总额   直选注数    金额  组三注数  金额.1   组六注数  \
0     2024275  2024-10-15  6  8  1  45724722  10880  1040     0   346  43826   
1     2024274  2024-10-14  2  7  4  46074198  15295  1040     0   346  41360   
2     2024273  2024-10-13  8  1  2  44565934  20896  1040     0   346  51346   
3     2024272  2024-10-12  4  3  6  45166252  13548  1040     0   346  40509   
4     2024271  2024-10-11  3  9  5  46392606  13831  1040     0   346  45845   
...       ...         ... .. .. ..       ...    ...   ...   ...   ...    ...   
7042  2004005  2004-11-22  0  5  4    915930    222  1000     0     0    604   
7043  2004004  2004-11-21  4  4  3   1442922    545  1000   400   320      0   
7044  2004003  2004-11-19  7  1  8   1605012    485  1000     0     0   1174   
7045  2004002  2004-11-16  3  1  7   1223202    415  1000     0     0   1457   
7046  2004001  2004-11-14  1  9  2   1170070    335  1000     0     0    889   

      金额.2  
0      173  
1      173  
2      173  
3      173  
4      173  
...    ...  
7042   160  
7043     0  
7044   160  
7045   160  
7046   160  

[7047 rows x 12 columns]

(7047, 4)

In [1]:
from modules.pretrain_timer import Timer
import torch
from utils.exp_config import get_config
config = get_config()
config.patch_len = 96
config.d_model = 1024
config.d_ff = 2048
config.e_layers = 8
config.n_heads = 8
config.dropout = 0.10
config.factor = 1
config.output_attention = 1
config.activation = 'gelu'
config.ckpt_path = 'Timer_forecast_1.0.ckpt'
backbone = Timer(config)
ckpt_path = 'Timer_forecast_1.0.ckpt'
sd = torch.load(ckpt_path, weights_only=False, map_location="cpu")["state_dict"]
sd = {k[6:]: v for k, v in sd.items()}
backbone.load_state_dict(sd, strict=True)

<All keys matched successfully>